name: Deploy Plugin Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip plugin
        run: zip -r plugin.zip ./plugin

      - name: Set Ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --local user.email "jcboy@foxmail.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin git@github.com:zjcboy/11-bacs-gateway.git
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" git push origin HEAD:main
          git push https://github.com/zjcboy/11-bacs-gateway.git HEAD:main

          
      - name: Commit plugin zip file
        run: |
          git add plugin.zip
          git commit -m "Add plugin zip file"


      - name: Purge Cloudflare Cache
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }} # You need to add this secret as well, representing your Cloudflare Zone ID
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
          -H "X-Auth-Email: $CF_EMAIL" \
          -H "X-Auth-Key: $CF_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
